generator_ckpt: logs/checkpoint_model_001200/model.pt
generator_fsdp_wrap_strategy: size
real_score_fsdp_wrap_strategy: size
fake_score_fsdp_wrap_strategy: size
real_name: Wan2.2-TI2V-5B
fake_name: Wan2.2-TI2V-5B
i2v: true
text_encoder_fsdp_wrap_strategy: size
warp_denoising_step: true # need to remove - 0 in denoising_step_list if warp_denoising_step is true
ts_schedule: false
num_train_timestep: 1000
timestep_shift: 5.0
guidance_scale: 5.0
denoising_loss_type: flow
mixed_precision: true
seed: 0
wandb_host: https://api.wandb.ai
wandb_key: 5409d3b960b01b25cec0f6abb5361b4022f0cc41
wandb_entity: liyitong-Tsinghua University
wandb_project: self-forcing
sharding_strategy: full
lr: 2.0e-06
lr_critic: 4.0e-07
beta1: 0.0
beta2: 0.999
beta1_critic: 0.0
beta2_critic: 0.999
data_path: prompts/MovieGenVideoBench_extended.txt
batch_size: 1
ema_weight: 0.99
ema_start_step: 200
total_batch_size: 4
log_iters: 200
meta_path: /lustre/fsw/portfolios/av/users/shiyil/jfxiao/AirVuz-V2-08052025/meta.csv
root_dir: /lustre/fsw/portfolios/av/users/shiyil/jfxiao/AirVuz-V2-08052025
negative_prompt: '色调艳丽，过曝，静态，细节模糊不清，字幕，风格，作品，画作，画面，静止，整体发灰，最差质量，低质量，JPEG压缩残留，丑陋的，残缺的，多余的手指，画得不好的手部，画得不好的脸部，畸形的，毁容的，形态畸形的肢体，手指融合，静止不动的画面，杂乱的背景，三条腿，背景人很多，倒着走'
dfake_gen_update_ratio: 3
image_or_video_shape:
- 1
- 48
- 21
- 30
- 40 
distribution_loss: ode
trainer: ode
gradient_checkpointing: true
num_frame_per_block: 3
load_raw_video: false
model_kwargs:
  timestep_shift: 5.0
  local_attn_size: 9
num_class: 2
resume_path: null
discriminator_warmup_steps: 50
eval_interval: 100
r1_weight: 100
r2_weight: 30
denoising_step_list:
- 1000
- 750
- 500
- 250